### ISSUE TITLE
Unable to automate site build

### ISSUE THREAD

**Issue by achafetz** [USAID-OHA-SI/grabr#2]
Get an error on GH Actions for site build.

![image](https://user-images.githubusercontent.com/8933069/184680281-12177731-d3e4-480c-a26b-4d2a1f0901aa.png)

https://github.com/USAID-OHA-SI/grabr/runs/7841550097?check_suite_focus=true

**Comment by baboyma** [comment]
This looks like it's solved - new version of R Studio 2022.1
