### ISSUE TITLE
Credential Issue > Error Message

### ISSUE THREAD

**Issue by achafetz** [USAID-OHA-SI/grabr#31]
When running the DATIM API, if you're credentials are outdated (ie you are using an old password) or you don't actually have access to the database you are hitting (eg final.datim.org), you get the following returned

> "<webMessage xmlns=\"[http://dhis2.org/schema/dxf/2.0\](http://dhis2.org/schema/dxf/2.0%5C)" httpStatus=\"Unauthorized\" httpStatusCode=\"401\" status=\"ERROR\"><message>Unauthorized</message></webMessage>"

Can we implement a error handling through `tryCatch` to provide a useful message back to the user saying to check their credentials or make sure they have access to the `baseurl`?

I had trouble with `tryCatch` but would this work @baboyma?

```
  test_creds <- function(username, password, baseurl){
      r <- httr::GET(baseurl, httr::authenticate(username, password))
    
    if(r$status_code == 401)
      usethis::ui_stop("No access to the url. Check that your credentials, used or stored, are current and that you have access to {baseurl}")
    }
```

Test
````
library(tidyverse)

  test_creds(glamr::datim_user(),
             "wrong password",
             "https://final.datim.org/api") 
  
  test_creds(glamr::datim_user(),
             glamr::datim_pwd(),
             "https://final.datim.org/api") 
  
```

**Comment by baboyma** [comment]
Agreed - definitely a tryCatch. 

Will update.

**Comment by baboyma** [comment]
Resolved and pushed to develop - ready for testing

**Comment by achafetz** [comment]
Looks good! Error came up immediately
![image](https://github.com/USAID-OHA-SI/grabr/assets/8933069/b69125c5-373b-4c24-aab7-d26c1d7af7ba)
