### ISSUE TITLE
pano_* testing

### ISSUE THREAD

**Issue by achafetz** [USAID-OHA-SI/grabr#47]
## Tests

```
devtools::load_all()

#test 1 - bad creds
pano_session("blah", "blah")

#test 2 - good creds
session <- pano_session()

#test3 - return items
url <- "https://pepfar-panorama.org/forms/downloads"
pano_items(url)

#test 4 - downloaded a specific url
url <- "https://pepfar-panorama.org/forms/downloads/Financial%20FY2023%20Q4%20Initial/Financial_Structured_Datasets_COP17-23_20231114.zip"
folder_path <- tempdir()
pano_download(url, dest = folder_path)
list.files(folder_path, "zip")

#test 5 - extract
pano_extract("financial")

#test 6 - extract msd
pano_extract_msd("Lesotho", level = "ou", dest_path = folder_path)

#test 7 - extract msds
pano_extract_msds("Lesotho", add_global = FALSE, items = "financial", dest_path = folder_path)
```

### Test 1
✅ Success (fails)

### Test 2
✅ Success 

### Test 3
➕ Success  - but `pano_items()` should utilize `lazy_secrets()`

### Test 4
✅ Success 

### Test 5
❌ Fail - ran into an unused argument for session. Also note that the folder destination param is `dest_path` where as in `pano_download()` it is `dest`

![image](https://github.com/USAID-OHA-SI/grabr/assets/8933069/12f40896-244d-4553-9895-d059ff9ce5d3)

### Test 6
❌ Fail - ran into an unused argument for session. Also note that the folder destination param is `dest_path` where as in `pano_download()` it is `dest`

![image](https://github.com/USAID-OHA-SI/grabr/assets/8933069/80b3679a-9489-4c66-bfac-25b93ef06a63)

### Test 7
❌ Fail - ran into an unused argument for session. Also note that the folder destination param is `dest_path` where as in `pano_download()` it is `dest`
![image](https://github.com/USAID-OHA-SI/grabr/assets/8933069/50316661-cc60-431d-bda0-f3b4294afd55)

**Comment by baboyma** [comment]
All great tests. The last 3 are related to the same issue: session vs user/pass. I have added both for pano_items and pano_extract.

All fixed now
